const mockData = {
  'code': 'success',
  'message': '',
  'result': [
    {
      'id': 1,
      'description': 'node',
      'link': 'http://nodejs.org',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 2,
      'description': 'uwp图标',
      'link': 'https://msdn.microsoft.com/zh-cn/library/windows/apps/windows.ui.xaml.controls.symbol.aspx',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 3,
      'description': '美团技术博客',
      'link': 'https://tech.meituan.com/all_the_papers_2016.html',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 4,
      'description': 'redux',
      'link': 'http://www.redux.org.cn/',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 5,
      'description': 'redux例子',
      'link': 'http://www.redux.org.cn/docs/basics/ExampleTodoList.html',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 6,
      'description': 'node',
      'link': 'http://nodejs.org',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 7,
      'description': 'uwp图标',
      'link': 'https://msdn.microsoft.com/zh-cn/library/windows/apps/windows.ui.xaml.controls.symbol.aspx',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 8,
      'description': '美团技术博客',
      'link': 'https://tech.meituan.com/all_the_papers_2016.html',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 9,
      'description': 'redux',
      'link': 'http://www.redux.org.cn/',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 10,
      'description': 'redux例子',
      'link': 'http://www.redux.org.cn/docs/basics/ExampleTodoList.html',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 11,
      'description': 'node',
      'link': 'http://nodejs.org',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 12,
      'description': 'uwp图标',
      'link': 'https://msdn.microsoft.com/zh-cn/library/windows/apps/windows.ui.xaml.controls.symbol.aspx',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 13,
      'description': '美团技术博客',
      'link': 'https://tech.meituan.com/all_the_papers_2016.html',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 14,
      'description': 'redux',
      'link': 'http://www.redux.org.cn/',
      'status': 1,
      'createdAt': null,
    },
    {
      'id': 15,
      'description': 'redux例子',
      'link': 'http://www.redux.org.cn/docs/basics/ExampleTodoList.html',
      'status': 1,
      'createdAt': null,
    },
  ],
  'total': 15,
};

export default mockData;
